POST http://localhost:3333/users
Content-Type: application/json

{
  "name":"John Smith",
  "email": "john@smith.com",
  "password": "123456"
}

###


POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "john@smith.com",
  "password": "123456"
}